### ISSUE TITLE
make naics codes easier to find

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-addin#12]
@nathankota this might be a good one to get some feedback on.

**Comment by nathankota** [comment]
By "I think hard coding it and updating the add-in when the data changes is fine.", do you mean scrapping the xlsx file as input, and manually updating the UICNAICSDomain at five year intervals (or whenever they change)?

**Comment by steveoh** [comment]
I'm not sure about the domain. I included the naics xlsx files in the add-in and they drive the query. I would assume the NAICS index file and the domain should be synced.

**Comment by steveoh** [comment]
I think the button is easy to find.
