### ISSUE TITLE
Add-in causes pro to crash on other projects

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-addin#18]
Need to add a state that will disable the addin from loading unless it is the uic mapping project.

**Comment by stdavis** [comment]
I think that this will be a common request. I'd love to know what you come up with. Perhaps we can make it a sharable module between projects.

**Comment by steveoh** [comment]
@stdavis I was initially thinking of using a [custom setting](https://github.com/Esri/arcgis-pro-sdk/wiki/ProGuide-Custom-settings#extra-considerations) that a user would `enable` for the project.

Do you think that is a good fit?

**Comment by stdavis** [comment]
That seems promising. So you'll have some sort of UI for the user to mark the current project as enabled for the addin?
