### ISSUE TITLE
mock up ribbon ui

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-addin#25]
create a mock up of the buttons for the add-in.

Things required

- [x] NAICS code finder
- [ ] Well validiation
- [ ] AOR validation
- [x] Feedback
- [ ] Some queries?

This is a running list

**Comment by steveoh** [comment]
![image](https://user-images.githubusercontent.com/325813/64205467-4c59b400-ce55-11e9-9d49-d46bc4cb4dee.png)

How does something like this look as a start @candkd

**Comment by CanDKD** [comment]
Yes, looks nice. I'll continue to identify other queries that need to be included under each table button.

**Comment by CanDKD** [comment]
Priorities for the Validation block of the Add In Ribbon: 
Find Well Issues; 
  Well - Check for No Well Operating Status Record
  Well - Check for No Authorization Record
  Well - Check for No AOR Record if AuthorizationType is IP or AP

Find Authorization Issues, 
  Authorization - Check for No AuthorizationAction Record
  Authorization - Check for No AreaOfReview Record if AuthorizationType is IP or AP

Find AOR Issues, 
  AOR - Check for No Artificial Penetration Record

Find Enforcement Issues,
  Enforcement - Check for Invalid EnforcementDate (enforcement date may not pre-date violation date of associated violation record.)

Find Violation Issues,
  Violation - Check for No Return to Compliance Date

**Comment by steveoh** [comment]
> can you have a Well drop down menu

**Comment by steveoh** [comment]
closed by 6052351b6d98ebae881ee09e19e641d7781fe00e
