### ISSUE TITLE
authorization validations

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-addin#30]
# Find Authorization Issues

- [x] Authorization - Check for No AuthorizationAction Record
- [ ] Authorization - Check for No AreaOfReview Record if AuthorizationType is IP or AP

**Comment by steveoh** [comment]
I did the `Check for No AreaOfReview Record if AuthorizationType is IP or AP` as part of the well buttons. Is this check for all authorizations or only well types @CanDKD

**Comment by CanDKD** [comment]
Check for No Authorization Record  resulted in this notification:
![image](https://user-images.githubusercontent.com/4369080/65180281-be1b2b80-da19-11e9-846d-358573785618.png)

even though my selected Authorization did not have an AuthAct record:
![image](https://user-images.githubusercontent.com/4369080/65180389-fcb0e600-da19-11e9-8877-d95f279b8d63.png)

from Version Table:
![image](https://user-images.githubusercontent.com/4369080/65180437-194d1e00-da1a-11e9-8a5c-d514173a0d90.png)

**Comment by steveoh** [comment]
I wonder if this is only for wells...

**Comment by CanDKD** [comment]
To see if this was a version-specific problem, I tried this logged in as UICADMIN pointed to the UIC_QA version; same issue.

**Comment by CanDKD** [comment]
I thought it was looking at all Authorization Records to see if there was a corresponding AuthorizationAction record?

**Comment by CanDKD** [comment]
I found 4 such instances

**Comment by CanDKD** [comment]
I was checking the 'Find Authorization without AuthorizationAction record' query sorry for the confusion.  I edited my first comment above.

**Comment by steveoh** [comment]
i think this is done
