### ISSUE TITLE
AOR Validations

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-addin#31]
# Find AOR Issues,

- [x] Find AORs with no Artificial Penetration Record
- [x] Find AORs without an Authorization

**Comment by CanDKD** [comment]
'Find AOR Issues' is not activated under Area of Review Validations.  Perhaps you haven't finished with this one yet??

**Comment by CanDKD** [comment]
Please add another query in the AOR Validation query set: 'Find AORs without an Authorization.'

**Comment by CanDKD** [comment]
I apologize for not explaining this.  The UICAreaOfReview tbl has a field NoArtPenDate.  This is the date it was determined that there were no artificial penetrations into the permitted injection zone.  If this field is not populated there should be at least one UICArtPen well associated with the AOR.  Also, remember there is a many to many relationship between UICAreaOfReview and UICArtPen so there isn't an AOR_FK in the UICArtPen record.
