### ISSUE TITLE
Add In Beta 3

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-addin#34]
This is the version in Pro on Monday Sept 9:
![image](https://user-images.githubusercontent.com/4369080/64538758-69b9d280-d2da-11e9-9fd8-1ced96b2b3e2.png)

This is what the UIC Tools menu looks like:
![image](https://user-images.githubusercontent.com/4369080/64538783-7dfdcf80-d2da-11e9-931d-6d9acd071101.png)
 I think we may have lost the Validation button.

**Comment by steveoh** [comment]
I just published beta 4. Please update to that and close this issue if that has the missing items.

**Comment by CanDKD** [comment]
After installation of Beta 4:
![image](https://user-images.githubusercontent.com/4369080/64546713-6a596580-d2e8-11e9-8202-7c5f36746086.png)

![image](https://user-images.githubusercontent.com/4369080/64546728-704f4680-d2e8-11e9-9d7d-d53a76040db5.png)
