### ISSUE TITLE
Notifications pane

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-addin#42]
Well Validations > no authorization query, which selects 4 wells.  the notification shows up in the transient (eventually fades away) UIC Add-In notification bubble and in the Notification pane.  I clear the selection then run the Well Validation > no area of review query.  The notification shows up in the transient UIC Add-In bubble but NOT in the Notification pane.  Can there be a piece of code each query that 'dismisses all' notifications?

**Comment by steveoh** [comment]
this is closed by 0d3261b433968f42ecfa3dca505e17c460c294c3
