### ISSUE TITLE
AOR Validations > no artificial penetrations

### ISSUE THREAD

**Issue by CanDKD** [agrc/uic-addin#43]
This query completely locks PRO such that I have to Ctrl Alt Del to get out.  I am unable to hit the SendFeedback button.  Progress bar as follows:

![image](https://user-images.githubusercontent.com/4369080/65629262-3fca0680-df90-11e9-8679-432ed9161821.png)

**Comment by steveoh** [comment]
i'm hoping 0d3261b433968f42ecfa3dca505e17c460c294c3 fixes this
