### ISSUE TITLE
SelectLayerByAttribute should use version views

### ISSUE THREAD

**Issue by steveoh** [agrc/uic-addin#44]
```[Error] GP Tool failure: ["CIMPATH=ccady_map/udeq_uicadmin_uicwell.xml", "NEW_SELECTION", "not exists (select 1 from UICWellOperatingStatus b where b.WELL_FK = UICWell.GUID)"] ["<msg code=\"358\" type=\"100\">ERROR 000358: Invalid expression</msg>", "<msg code=\"-2147467259\" type=\"100\">Failed to execute (SelectLayerByAttribute).</msg>"]```

**Comment by CanDKD** [comment]
When I run the Add In logged in as UICAdmin for versions Default or UIC_QA for which I am the Owner the 'no artificial penetration' query runs.  However, logged in as CCady and running AddIn against UIC_CCady the query doesn't run; locks up Pro.

**Comment by steveoh** [comment]
Thank you for filling in the repro details

**Comment by steveoh** [comment]
This isn't for the no artificial penetration, this is for the #46 so i'm going to close this as a duplicate
